package rules.submiss.createDocs;

import ch.bern.submiss.services.api.dto.CompanyDTO;
import ch.bern.submiss.services.api.dto.SubmissionDTO;
import ch.bern.submiss.services.api.dto.DocumentDTO;
import ch.bern.submiss.services.api.dto.CountryHistoryDTO;
import java.util.HashMap;
import java.util.Date;
import ch.bern.submiss.services.api.util.SubmissConverter;

global HashMap placeholderMappings;

rule "FT04"
	when
		$company: CompanyDTO()
		$document: DocumentDTO()
	    if($company.getAddress2() != null) do[address2]
	    else do [address2Empty]
	    if($company.getCompanyFax() != null && ($company.getCompanyFax().length() > 5)) do[companyFax]
	    else do [companyFaxEmpty]
	     if($company.getTlp() != null && $company.getTlp()) do[companyTlp]
	    else do [companyTlpEmpty]
	    if( $company.getMainCompany() != null) do[companyMain]
	    else do [companyMainEmpty]
	    if( $company.getCompanyWeb() != null) do[companySite]
	    else do [companySiteEmpty]
                  if( $company.getNoteAdmin() != null) do[NoteAdmin]
	    else do [NoteAdminEmpty]
	    if( $company.getNotes() != null) do[Notes]
	    else do [NotesEmpty]
	    if( $company.getNumberOfWomen() != null) do[numberWomen]
	    else do[numberWomenEmpty]	
	then
 	    placeholderMappings.put("s_current_date", SubmissConverter.convertToSwissDate(new Date()));
	    placeholderMappings.put("f_company_address", $company.getAddress1());
	    placeholderMappings.put("f_company_post", $company.getPostCode());
	    placeholderMappings.put("f_company_location", $company.getLocation());
	    placeholderMappings.put("f_company_name", $company.getCompanyName());
	    placeholderMappings.put("f_company_tel", $company.getCompanyTel());
	    placeholderMappings.put("f_country", $company.getCountry().getCountryName());
	    placeholderMappings.put("f_company_mail", $company.getCompanyEmail());
	    placeholderMappings.put("s_current_date", SubmissConverter.convertToSwissDate(new Date()));
	    placeholderMappings.put("f_company_apprenticeFactor", String.valueOf(($company.getNumberOfMen() == null ? 0 : $company.getNumberOfMen()) +
($company.getNumberOfWomen() == null ? 0 : $company.getNumberOfWomen()) + " MA, " + String.valueOf(($company.getNumberOfTrainees() == null) ? 0 : $company.getNumberOfTrainees()) + " LL"));
        placeholderMappings.put("f_company_ilo",($company.getIloDate() == null ? " " : SubmissConverter.convertToSwissDate($company.getIloDate())));
        placeholderMappings.put("f_company_logib", ($company.getLogIb() ? ($company.getLogibDate() != null ? SubmissConverter.convertToSwissDate($company.getLogibDate())  : "ausstehend" ) : "-" ));
        placeholderMappings.put("f_fifty_plus_factor", String.valueOf(($company.getNumberOfMen() == null ? 0 : $company.getNumberOfMen()) +
($company.getNumberOfWomen() == null ? 0 : $company.getNumberOfWomen()) + " MA, " + String.valueOf(($company.getFiftyPlusColleagues() == null) ? 0 : $company.getFiftyPlusColleagues()) + " MA 50+"));
	    
	then[address2]
	    placeholderMappings.put("f_company_address2", $company.getAddress2());
	then[address2Empty]
	    placeholderMappings.put("f_company_address2", "");
	then[companyFax]
	    placeholderMappings.put("f_company_fax", $company.getCompanyFax());
	then[companyFaxEmpty]
	    placeholderMappings.put("f_company_fax", "");
	then[companyTlp]
	    placeholderMappings.put("f_company_tlp", "Ja");
	then[companyTlpEmpty]
	    placeholderMappings.put("f_company_tlp", "Nein");
	then[companyMain]
	    placeholderMappings.put("f_company_main", $company.getMainCompany().getCompanyName());
	then[companyMainEmpty]
	    placeholderMappings.put("f_company_main", "");
	then[companySite]
	    placeholderMappings.put("f_company_site", $company.getCompanyWeb());
	then[companySiteEmpty]
	    placeholderMappings.put("f_company_site", "");    
     then[Notes]
	     placeholderMappings.put("f_company_notes", $company.getNotes()); 
	 then[NotesEmpty] 
	     placeholderMappings.put("f_company_notes", "");
 	then[NoteAdmin]
	     placeholderMappings.put("f_company_notesAdm", $company.getNoteAdmin()); 
	 then[NoteAdminEmpty] 
	     placeholderMappings.put("f_company_notesAdm", "");
	 then[numberWomen]
	     placeholderMappings.put("f_company_number_of_women" , $company.getNumberOfWomen().toString());		
	then[numberWomenEmpty]
	     placeholderMappings.put("f_company_number_of_women" , "");	    
	end