package rules.submiss.createDocs;

import ch.bern.submiss.services.api.dto.CompanyDTO;
import ch.bern.submiss.services.api.dto.SubmissionDTO;
import ch.bern.submiss.services.api.dto.DocumentDTO;
import java.util.HashMap;
import ch.bern.submiss.services.api.util.SubmissConverter;

global HashMap placeholderMappings;

rule "PT03"
	when
		$company: CompanyDTO()
		$document: DocumentDTO()
	if ($company.getAddress2() != null) do[address2]
	else do[address2Empty]	
	then
		placeholderMappings.put("f_company_name", $company.getCompanyName());
		placeholderMappings.put("f_proofDate", SubmissConverter.convertToSwissDate($document.getSubmitDate()));
		placeholderMappings.put("f_company_post", $company.getPostCode() + " " + $company.getLocation());
	then [address2]
		placeholderMappings.put("f_company_address", $company.getAddress1() + "\\n" + $company.getAddress2());
	then [address2Empty]	
		placeholderMappings.put("f_company_address", $company.getAddress1());
	end